build:
    environment:
        php: 7.0.6
    tests:
        override:
            -
                command: 'ant test'
                coverage:
                    file: 'build/logs/clover.xml'
                    format: 'clover'
filter:
    paths: [src/*]
    excluded_paths: [README.md, Tests/*, vendor/*, build/*, Resources/*, var/*]
checks:
    php:
        code_rating: true
        duplication: true
tools:
    php_analyzer:
        enabled: true
        extensions:
            - php
    external_code_coverage:
        timeout: 600
        runs: 1
    php_code_coverage: false
    php_code_sniffer:
        config:
            standard: PSR2
        filter:
            paths: [Factory, Traits]
    php_loc:
        enabled: true
        excluded_dirs: [vendor, spec]
    sensiolabs_security_checker:
        enabled: true
